source("loadData.R")
dev.off()
plot(power_table_subset$DateTime,power_table_subset$Global_active_power,type = "l", xlab="",ylab="Global Active Power (Kilowatts)")
dev.copy(png,file="plot2.png", width = 480, height=480)
dev.off()
cat("File plot2.png has been saved in ,",getwd())
